name: Check Quiz Answers

on:
  pull_request:
    branches:
      - main

jobs:
  check-answers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Up Correct Answers
        run: |
          echo "1: ${{ secrets.ANSWER_1 }}" > correct_answers.txt
          echo "2: ${{ secrets.ANSWER_2 }}" >> correct_answers.txt
          echo "3: ${{ secrets.ANSWER_3 }}" >> correct_answers.txt
          echo "4: ${{ secrets.ANSWER_4 }}" >> correct_answers.txt
          echo "5: ${{ secrets.ANSWER_5 }}" >> correct_answers.txt

      - name: Extract Participant Answers
        run: |
          ANSWER_FILE=$(find . -name "quiz_answers_*.txt" | head -n 1)
          if [ -z "$ANSWER_FILE" ]; then
            echo "No answer file found!"
            exit 1
          fi

          grep -o '^[0-9]*: \[x\].*' "$ANSWER_FILE" | sed 's/^\([0-9]*\): \[x\] \(.*\)/\1: \2/' > participant_answers.txt

      - name: Compare Answers
        run: |
          if diff correct_answers.txt participant_answers.txt; then
            echo "Answers correct. Ready to merge."
          else
            echo "Answers incorrect. Auto-merge not allowed."
            exit 1
          fi
